services:
  traefik:
    image: traefik:v3.0
    container_name: traefik_test
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/traefik.yml:/traefik.yml
      - ./data:/data
      - ./data/config.yml:/config.yml:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`monitor.<redacted>.com`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
    networks:
      - proxy
networks:
  proxy:
    external: true